### ISSUE TITLE
Updating Readme file

### ISSUE THREAD

**Issue by ShafiMohammad09** [maddox05/Auto-Clicker#4]
Hi there @maddox05 👋,
i'm enthusiastic about contributing to the project and I believe that improving the README file could greatly benefit its usability and accessibility for new contributors.

If you think it's a valuable initiative, I'd be happy to take the lead on this task. I can start by reviewing and updating the existing content, ensuring it provides clear instructions and relevant information for potential contributors.

Please let me know your thoughts on this, and if you have any specific guidelines or preferences in mind.

**Comment by maddox05** [comment]
go for it! thank you!
